---
appveyor.yml:
  delete: true
.travis.yml:
  docker_sets: []

Gemfile:
  optional:
    ':development':
      - gem: 'rbvmomi'
      - gem: 'hocon'
    ':acceptance':
      - gem: 'mustache'
        version: '0.99.8'

LICENSE:
  license_type: 'puppetpe'

Rakefile:
  unmanaged: true
